# Generated by Django 4.0.3 on 2022-03-28 16:39

import cloudinary.models
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.CharField(choices=[('Fashion and Clothing', 'FASHION & CLOTHING'), ('Food and Drinks', 'FOOD & DRINKS'), ('Electronics', 'ELECTRONICS'), ('Kids and Babies', 'KIDS & BABIES'), ('Jewelry and Accessories', 'JEWELRY & ACCESSORIES'), ('Home and Decor', 'HOME & DECOR'), ('Arts and Craft', 'ART & CRAFT'), ('Beauty and Wellness', 'BEAUTY & WELLNESS'), ('Pets and Animals', 'PETS & ANIMALS'), ('Books and Publishers', 'BOOKS & PUBLISHERS')], max_length=55)),
                ('price', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=200)),
                ('precise_location', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('negotiatable', models.BooleanField(default=False)),
            ],
        ),
    ]
